### ISSUE TITLE
node-auth0 integration

### ISSUE THREAD

**Issue by saltukalakus** [auth0-extensions/auth0-reset-tenant#22]
We could introduce a new API layer consumed by our recipes. This API layer could use node-auth0 or some other custom libs. Custom libs are used when node-auth0 can not handle the case properly.

**Comment by twistedstream** [comment]
Yep, I think this is a great idea. I'd like to use this concept to improve the recipe authoring experience. Specifically:

* Replace the use of `import`s of helper modules with API instances built into the `run` parameters
* Remove the the `accessTokens` parameter and replace it with APIs instances that already have the required `access_token` so the author doesn't have to worry about them at all
* Create APIs that provide more explicit functions like `createConnection` instead of `createEntity`.

In nutshell go from this:

```js
import * as auth0 from '../lib/auth0';

export const run = (accessTokens) => {
  return auth0.createEntity('Client', 'client_id', '/api/v2/clients', accessTokens.v2, {
    name: 'My Website',
    callbacks: [ 'http://localhost:3000/callback' ],
    app_type: 'regular_web',
    jwt_configuration: { alg: 'RS256' }
  });
};
```

to this:

```js
export const run = (context) => {
  return context.auth0.createConnection({
    name: 'My Website',
    callbacks: [ 'http://localhost:3000/callback' ],
    app_type: 'regular_web',
    jwt_configuration: { alg: 'RS256' }
  });
};
```
